[build-system] 
requires = ["setuptools"] 
build-backend = "setuptools.build_meta" 
[project] 
name = "imageClassifier" 
version = "0.0.1" 
dependencies = [] 
requires-python = ">=3.11" 
authors = [ 
{name = "", email = ""}, 
] 
readme = "README.md" 
